### ISSUE TITLE
Still nicer printing of exceptions?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#100]
We currently might print something like this:
```
With exceptions:
  (2*n1)//(q - 1) ∈ ℤ
```
personally I would find this much easier to grasp:
```
With exceptions:
  2*n1 ∈ (q - 1)ℤ
```
Could we perhaps do that? Or are there complications, such as cases were it would be *worse* than what we have now?

**Comment by SoongNoonien** [comment]
> Could we perhaps do that? Or are there complications, such as cases were it would be worse than what we have now?

I don't see any problems with this.
