### ISSUE TITLE
Is `congruence` handling in tables working as intended?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#114]
Looking at many tables, e.g. `data/Tables/2B2/2B2.jl`, they make use of a `congruence` variable for class sums and char sums. In the named table for example, we find:
```julia
classsums=[
function (tt::Cyclotomic)
	tt
end,
function (tt::Cyclotomic)
	tt
end,
function (tt::Cyclotomic)
	tt
end,
function (tt::Cyclotomic)
	tt
end,
function (tt::Cyclotomic)
	s1=nesum(tt, a, 1, 2*q0^2-2, congruence)
	1//2*s1
end,
function (tt::Cyclotomic)
	s1=nesum(tt, b, 1, 2*q0^2+2*q0, congruence)
	1//4*s1
end,
function (tt::Cyclotomic)
	s1=nesum(tt, c, 1, 2*q0^2-2*q0, congruence)
	1//4*s1
end
]
```
Note how `congruence` is *not* an argument to the table (nor are `a,b,c,q0` for that matter). So by Julia's rules it refers to that variable in the containing module, which is defined in line 162 as
```julia
congruence=nothing
```

Fair enough... But I see no way how anything in our existing code would be able to change the value of that variable. In particular, I had a look at how `setcongruence` is implemented, and as far as I can tell, it doesn't modify this variable.

So now I am wondering... am I missing something? If I am right: then is code using the char/class sums even correct? Maybe it is correct, just less efficient? Or maybe it *needs* to be separate from the `congruence` stored in the table?

All in all this is extremely dodgy and needs to be fixed. Of course on the long run the hope is that we can get rid of these functions and replace them by generic code. But I am not sure how close that is. In the meantime, perhaps we could turn `congruence` into an argument for those sum functions (or perhaps have the entire table an argument). Or if the `congruence` value really should stay as it is, then we should at least turn all definitions of `congruence` in table files into constants, i.e., in this example `const congruence = nothing` -- that would make it clear that this value must stay, and would also allow some additional (very minor) optimizations.

**Comment by SoongNoonien** [comment]
This has been fixed in #139.
