### ISSUE TITLE
Collect bibliography

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#115]
Many tables contain bits like this:
```
- The table was first computed in:
  {\sc M. Suzuki}, On a class of doubly transitive groups, {\em Ann. of
    Math. \bf75} (1962), 105--145.
```
We should collect these references into a `.bib` file (actually I am adding on in PR #104 -- I'll look into pulling that out into a separate PR that can be merged ASAP).

The easiest way to get good quality bibtex entries for this is to use https://zbmath.org and/or https://mathscinet.ams.org/ to search for e.g. the title; once you have found the right item, both sites offer copying BibTeX data.

E.g. on https://zbmath.org/0106.24702 there is a little BibTeX button in the lower right, which gives this:
```
@Article{zbMATH03173723,
 Author = {Suzuki, Michio},
 Title = {On a class of doubly transitive groups},
 FJournal = {Annals of Mathematics. Second Series},
 Journal = {Ann. Math. (2)},
 ISSN = {0003-486X},
 Volume = {75},
 Pages = {105--145},
 Year = {1962},
 Language = {English},
 DOI = {10.2307/1970423},
 URL = {hdl.handle.net/2027/mdp.39015095249804},
 zbMATH = {3173723},
 Zbl = {0106.24702}
}
```
while on https://mathscinet.ams.org/mathscinet/article?mr=136646 there is a blue link on the right side just saying "Cite" which when clicked offers copying a citation in one of various formats, default being (for me at least) BibTeX. Here it gives:
```
@article {MR0136646,
    AUTHOR = {Suzuki, Michio},
     TITLE = {On a class of doubly transitive groups},
   JOURNAL = {Ann. of Math. (2)},
  FJOURNAL = {Annals of Mathematics. Second Series},
    VOLUME = {75},
      YEAR = {1962},
     PAGES = {105--145},
      ISSN = {0003-486X},
   MRCLASS = {20.29},
  MRNUMBER = {136646},
MRREVIEWER = {W.\ Feit},
       DOI = {10.2307/1970423},
       URL = {https://doi.org/10.2307/1970423},
}
```

**Comment by SoongNoonien** [comment]
Note to myself: Remember to add Kempner's paper for #82.

**Comment by fingolfin** [comment]
Talking with @SoongNoonien and @ThomasBreuer about this during OSCAR workshop. Two ideas for using the bib data when we have it:
1. generate a page / pages in the manual with a list of all table, and also for each table
2. for each paper, list which tables resulted from it

In an ideal world these connections (which form a graph) would be computable by querying our data (that means each table object would need to contain a vector/list of the bib items it references)

**Comment by fingolfin** [comment]
Thanks to @SoongNoonien we now have a bib file with many nice entries, now we just have to make use of it ;-)
