### ISSUE TITLE
Should tables be made immutable (at least the main data)?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#13]
Functions like `tensor!` and `lincomb!` currently add new rows to the tables.

This is, as far as I can tell, the main reason there is a type `ExtendableMatrix`.

But what is not clear to me is *why* this is done. Logically it would seem much cleaner to me if there was a separate type for `GenericCharacter`. The rows of the `GenericCharacterTable` then would be `GenericCharacter` objects, each with a pointer to its "parent table". And tensor products, linear combinations etc. would then be the same.

Perhaps @SoongNoonien can explain if this is just an artifact of how the original code was organized, or if there are deeper reasons for this.

**Comment by fingolfin** [comment]
Related but a bit different: `speccharparam!` and `specclassparam!` modify the table in-place -- but perhaps there it makes a bit more sense. Though it would be good if there was an easy way to tell if a table is modified, and how

**Comment by SoongNoonien** [comment]
> Perhaps @SoongNoonien can explain if this is just an artifact of how the original code was organized, or if there are deeper reasons for this.

This is indeed just an artifact of the original implementation.

**Comment by SoongNoonien** [comment]
> speccharparam! and specclassparam! modify the table in-place -- but perhaps there it makes a bit more sense. Though it would be good if there was an easy way to tell if a table is modified, and how

The `charparams` and `classparams` fields of `CharTable` store which parameters were specified a thus how the table was modified by `speccharparam!` and `specclassparam!`.

**Comment by fingolfin** [comment]
Excellent to hear!

Regarding `charparams` and `classparams`, my main idea was that a `show` method for character tables should state this. E.g. 
```
Generic character table GL2 
  with parameters i, j, l, k
  with specialization i=1
  ...
```

**Comment by SoongNoonien** [comment]
I'd say the only problem remaining here is `specclassparam!`, isn't it?

**Comment by fingolfin** [comment]
Indeed

**Comment by fingolfin** [comment]
We could handle it for now by changing it to return a new modified table instead of modifying the input table (and then drop the `!` from its name)

**Comment by SoongNoonien** [comment]
`specclassparam!` is gone now, it has been fully replaced by `specialize`.
