### ISSUE TITLE
Add improved normal form and simplification algorithms

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#15]
In his Bachelor thesis, @SoongNoonien described algorithms for computing normal forms for generic cyclotomics.

These algorithms should be implemented here and made use of in various places.

Also, his thesis should be turned into a paper which then can be referenced in the code for explanations, proofs of correctness etc.

**Comment by fingolfin** [comment]
In particular I think this new code would be used to replace `nesum`?

And also perhaps allow replacing some information that is currently hardcoded, such as the `classsums` and `charsums` vectors? Maybe not, I need to understand this better again first.

**Comment by SoongNoonien** [comment]
> In particular I think this new code would be used to replace nesum?

The problem with `nesum` is that it can produce false results with certain input values. But at least to my knowledge/hoping this will not happen when using it for generic character tables. So actually we should just catch these cases where false results are possible. But in my thesis there is a proof of why and when `nesum` works which was at least to me not very obvious at first.

> And also perhaps allow replacing some information that is currently hardcoded, such as the classsums and charsums vectors?

Yes, this would certainly be nice but I didn't get there in my thesis. It shouldn't mathematically hard though.

I think the main file that needs refactoring is `Arith.jl` especially the `normalize` (`normal_form` #12) functions which are incomplete in the sense of producing different normal forms for equivalent inputs.
