### ISSUE TITLE
Exceptions list changed?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#158]
While updating the book example test PR #104 I've noticed the following changed. Begun with this setup:
```julia
T = genchartab("SL3.n1"); h = T[2] * T[2]; scalar(T[4], h)
```
Now some time ago, we got this output:
```
0
With exceptions:
  -2*n1 ∈ (q - 1)ℤ
```
but this has now changed to the following -- which is equivalent, but clearly not fully simplified, because the first exception includes the second one, which hence is redundant.
```
0
With exceptions:
  -2*n1 ∈ (q - 1)ℤ
  -n1 ∈ (q - 1)ℤ
```

**Comment by fingolfin** [comment]
Ah, only after filing this did I noticed PR #155 which perhaps already addresses this?

**Comment by SoongNoonien** [comment]
Yes, #155 addresses this.
