### ISSUE TITLE
Deal with `irrchartypes` and `chartypes`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#159]
The two function should now always return the same value, as we don't allow changing the table anymore.

I would move both the deprectation file. Instead, there should be a `length(::Table)` method. That would fit in with the use of `T[i]` to access the i-th (irreducible) character type.

**Comment by fingolfin** [comment]
I guess this means we can also get rid of the `::irrchartypes` field in the table structs.

**Comment by SoongNoonien** [comment]
Yes, this seems reasonable.

**Comment by fingolfin** [comment]
BTW, I realize there is is overlap with issue #110, but that one was maybe too generic. I hope this very specific one can be deal with quickly, and then I can further elaborate in #110 (or close it in favor of other more concrete issues)
