### ISSUE TITLE
Alternative to `printcharparam`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#166]
We should deprecate or delete `printcharparam`. Instead there should be a function which takes a generic character and gets it parameters.

In Oscar we have `character_parameters` (CC @ThomasBreuer) but that is called on the full table, and I am not sure if those parameters are comparable to what we have. So I'd be tempted so say there simply should be a function `params` (or `parameters`?) which takes a single character and returns its `params`. Perhaps we also allow `nothing` if there are none (e.g. for simple tables). Or perhaps an empty params object should be returned, dunno, both is fine by me. Perhaps @SoongNoonien has a preference?

**Comment by SoongNoonien** [comment]
I'm not a big fan of `params` as we do have this already for `CharTable` but with a slightly different meaning.

**Comment by ThomasBreuer** [comment]
Concerning the attribute `character_parameters`, this refers to specializations of a generic table.
For example, the table of GL(2, q) has four types of characters (and classes), and each type has its parameter range.
```
julia> class_parameters(character_table(:GL2, 2))
3-element Vector{Tuple{Int64, Int64}}:
 (1, 0)
 (2, 0)
 (4, 1)
```
The first entry of each tuple is the type number, the second entry is the parameter value for the given type.
For q = 2, there is no character of type 3, and there is exactly one character of each of the other types.

My interpretation is that in a generic character table, each character stands for the irreducibles of its type, and the parameters of the character mean the parameter range of the type.
In this sense, the parameters of a generic table and specialized tables should be compatible, but they describe different information.

**Comment by SoongNoonien** [comment]
> My interpretation is that in a generic character table, each character stands for the irreducibles of its type, and the parameters of the character mean the parameter range of the type.
In this sense, the parameters of a generic table and specialized tables should be compatible, but they describe different information.

Ok, I'd say they are different enough that `character_parameters` could be confusing.

We have replaced `printcharparam` by `params` already. So, I think we can close this issue and continue thinking about it in #180.
