### ISSUE TITLE
Rename or split `params`

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#180]
The `params` function for generic characters I added for the book example clashes with the existing `params` function for the tables in the sense that on the surface it seems as if they do very similar things (return information about the parameters...) but in practice they work very differently.

Perhaps `params(chi::AbstractGenericCharacter)` should be split into three functions
- `params` returns a vector/tuple/whatever of variables, similar to `params(::Table)`
- `exceptions(char)` returns a the parameter exceptions 
- `ranges(char)` or maybe `parameter_ranges` or whatever returns the information about the "admissible" ranges for the various parameters (in some format to be determined).

In the old system the details were not so important because the information was only meant to be read by a human user (hence usually we just had `printFOOBAR` functions to print them).

But as we work towards the vision in #28, we'll have a lot of need to interact programmatically with this data, so it may be worthwhile to think about how we can best make it available.

E.g. my feature request #178 for `specialize` also involves the question how we let the user access the exceptions list.

**Comment by fingolfin** [comment]
This needs to be dealt with quickly as it'll affect the book content. Thoughts, @SoongNoonien ?

**Comment by SoongNoonien** [comment]
I think we could do it how you proposed it. But I'm not sure if `exceptions` and `ranges` can be separated that easily. Only in combination they specify which values are allowed and which aren't. Also note that even in combination they currently don't completely specify the admissible values; some value combinations lead to the same character. We already noticed this while looking into removing the summation functions. So in the future we have to come up with a different or at least an extended format to completely specify all and only the allowed parameter combinations. This format will have a new kind of restriction.

**Comment by SoongNoonien** [comment]
> So I'll turn this around: would there even be any utility in having a function that takes a character and returns the variables that are used in it? I.e. that does what `params(table)` resp. `params(parent(char))` does, just perhaps restricting to the variables occurring in the character?

And don't think we need this.

> Right now I don't see any need for that. Programatic resolution of exceptions may require access to variables, but they would be obtained from the `ParameterExceptions` object.

Yes, exactly.

> So perhaps it is indeed OK to leave things as they are?

Yes, we need to rework/replace the interface for getting and creating new parameters for a table anyway. See for example #28 and #178. So in the future we won't have `params(::Table)` anymore removing the possible confusion.

> BTW, part of what confuses me here is that there are two very different (to my eye at least) ways in which exceptions turn up:...
For the latter case it seems sensible and prudent to be able to access individual exceptions.

So something like `exceptions(::GenericCycloFrac)`? Then we would also need a `getindex` and `iterate` for `ParameterExceptions`.

**Comment by SoongNoonien** [comment]
> So something like `exceptions(::GenericCycloFrac)`?

I just realize you already mentioned this in #178.
