### ISSUE TITLE
Mention new sugary bits in the docs

### ISSUE THREAD

**Issue by SoongNoonien** [oscar-system/GenericCharacterTables.jl#186]
> Actually, I think it would be good to see the printing of the substituted character (this then also serves as a test case for that).
Moreover, I am not sure if users who come to us from CHEVIE will appreciate this kind of cleverness in the documentation. They'll first have to figure out what `collect` invoked on a character even *means*, and we don't explain that anywhere (`?collect` certainly won't help either).
So while I approve of this feature, I am not sure it is wise to use it here. 
What we however *should* do (in a future PR) is expand the manual to mention that generic characters & tables implement the Julia iteration interface, and what that means, together with some examples as `jldoctest`. Something like "For example, we can use `collect` on a generic character to obtain a vector of its values:" followed by a jldoctest example.
Perhaps you can file an issue to remind us to do that?

_Originally posted by @fingolfin in https://github.com/oscar-system/GenericCharacterTables.jl/pull/181#discussion_r1773220989_

So we should mention in the docs that one can iterate over generic characters and tables. Also the `length` and `getindex` methods are worth mentioning.

**Comment by fingolfin** [comment]
In the revised manual structure introduced in PR #185 there is a very natural place (or rather: two) where to add these: just add a new section "Iteration" or so to tables.md resp. characters.md

**Comment by fingolfin** [comment]
Since I am working on the docs now anyway I can take of this along the way.

**Comment by SoongNoonien** [comment]
Ok, I was just looking for nice examples. Maybe an interesting one is, that we can recompute the order of a group very easily now:

```
julia> sum(nrchars(c)*degree(c)^2 for c in g)
q^4 - q^3 - q^2 + q

julia> order(g)
q^4 - q^3 - q^2 + q

```

In this example `g` is $\text{GL}(2,q)$.
