### ISSUE TITLE
Bug in `scalar` function?

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#25]
It seems the `scalar` function almost always returns `0` as scalar product (the exception being products of a character with itself, which gives the norm). At least in all examples I tried. Including examples where I have reference values from the paper
> [CHEVIE - A system for computing and processing generic character tables](https://link.springer.com/article/10.1007/BF01190329) ([alternate PDF](http://www.math.rwth-aachen.de/~Frank.Luebeck/preprints/CHEVIE_AAECC.pdf))

There, in section 5.3, the table `SL3.n1` is used, and certain scalar products are computed. E.g. there:
```
Scalar_SL3.n1,h(1,1) = 1
Scalar_SL3.n1,h(2,1) = 2
Scalar_SL3.n1,h(3,1) = 2
   Possible Exceptions: {[2*nN1, q-1]}
Scalar_SL3.n1,h(4,1) = 0
   Possible Exceptions: {[2*nN1, q-1]}
```
But in this package I get:
```
julia> T = genchartab("SL3.n1");

julia> scalar(T,1,1)
(1, Set{GenericCharacterTables.ParameterException{Nemo.QQPolyRingElem}}())

julia> scalar(T,2,1)
(0, Set{GenericCharacterTables.ParameterException{Nemo.QQPolyRingElem}}())

julia> scalar(T,3,1)
(0, Set{GenericCharacterTables.ParameterException{Nemo.QQPolyRingElem}}())

julia> scalar(T,4,1)
(0, Set(GenericCharacterTables.ParameterException{Nemo.QQPolyRingElem}[2//(q - 1)*n1 ∈ ℤ]))
```
So at least the two middle values seem wrong, and the exceptions for 3,1 are missing.

For 4,1 the exception in the original apparently means that `q-1` must not divide `2*nN1` for the general case, i.e., there is an exception when  `2*nN1/(q-1)` is an integer... which looks what we have, so that at least is good.

@SoongNoonien any ideas? Am I doing something wrong?

**Comment by fingolfin** [comment]
For this character table, only the scalar products of the characters 1,2,3 with themselves are non-zero (namely equal to 1):
```
julia> [(i,j) for i in 1:8, j in 1:8 if !iszero(scalar(T,i,j)[1])]
3-element Vector{Tuple{Int64, Int64}}:
 (1, 1)
 (2, 2)
 (3, 3)
```

**Comment by fingolfin** [comment]
Nevermind: I think I interpreted the paper wrong, the character "1" there is actually a character in another table which is the tensor product...

Just to add: of course in general I'd expect irreducible character to be pairwise orthogonal, so then 0 would be expected. But some of the character types can overlap, i.e. the same irreducible character can be in two different character types, leading to non-zero scalar products.

But I am still surprised that e.g. `scalar(T,4,4)` gives 0... But there are lots of exceptions there:
```
julia> scalar(T,4,4)
(0, Set(ParameterException{Nemo.QQPolyRingElem}[1//(q - 1)*n2 ∈ ℤ, 2//(q - 1)*n1 + 1//(q - 1)*n2 ∈ ℤ, 1//(q - 1)*n1 + 2//(q - 1)*n2 ∈ ℤ, 1//(q - 1)*n1 + 1//(q - 1)*n2 ∈ ℤ, 1//(q - 1)*n1 ∈ ℤ, 2//(q - 1)*n1 - 2//(q - 1)*n2 ∈ ℤ]))
```

**Comment by fingolfin** [comment]
Looks much better for the tensor:
```
julia> T = genchartab("SL3.n1");

julia> tensor!(T,2,2)
9

julia> for i in 1:8
         println()
         s,e=scalar(T,i,9)
         println("scalar($i,9) = ", s)
         e = collect(e)
         if !isempty(e) println(" Possible exceptions: ") ; display(e) end
       end

scalar(1,9) = 1

scalar(2,9) = 2

scalar(3,9) = 2

scalar(4,9) = 0
 Possible exceptions:
1-element Vector{ParameterException{Nemo.QQPolyRingElem}}:
 2//(q - 1)*n1 ∈ ℤ

scalar(5,9) = 0
 Possible exceptions:
1-element Vector{ParameterException{Nemo.QQPolyRingElem}}:
 2//(q - 1)*n1 ∈ ℤ

scalar(6,9) = 0
 Possible exceptions:
6-element Vector{ParameterException{Nemo.QQPolyRingElem}}:
 1//(q - 1)*m1 + 1//(q - 1)*n1 ∈ ℤ
 2//(q - 1)*m1 - 1//(q - 1)*n1 ∈ ℤ
 1//(q - 1)*m1 ∈ ℤ
 1//(q - 1)*n1 ∈ ℤ
 1//(q - 1)*m1 - 1//(q - 1)*n1 ∈ ℤ
 1//(q - 1)*m1 - 2//(q - 1)*n1 ∈ ℤ

scalar(7,9) = 0
 Possible exceptions:
1-element Vector{ParameterException{Nemo.QQPolyRingElem}}:
 1//(q - 1)*n1 ∈ ℤ

scalar(8,9) = 0
 Possible exceptions:
3-element Vector{ParameterException{Nemo.QQPolyRingElem}}:
 (q + 1)//(q^2 + q + 1)*n1 ∈ ℤ
 q//(q^2 + q + 1)*n1 ∈ ℤ
 1//(q^2 + q + 1)*n1 ∈ ℤ

```

It seems the paper lists the exceptions *before* the scalars they belong to, so I was reading that bit wrong. The output above now matches what is in the paper. Excellent

**Comment by SoongNoonien** [comment]
> But I am still surprised that e.g. scalar(T,4,4) gives 0... But there are lots of exceptions there:

Yes, we were surprised by this as well. But if understand it correctly this is due to the fact that most of the actual characters in the character type 4 are not the same an thus linearly independent. Only if some of the exceptions hold we are actually computing a scaler product of two equal characters. The results of `scalar(i,j)` actually correspond to some kind of matrix where the rows correspond to the characters in the character type `i` and the columns to the characters of type `j`. And then only the diagonal should be one if `i=j`, all other entries should be zero in this case.
