### ISSUE TITLE
Add a `degree` method for characters

### ISSUE THREAD

**Issue by fingolfin** [oscar-system/GenericCharacterTables.jl#31]
For now something like this could work.
```julia
degree(t::Table, i::Int) = t.chardegree[i]
```
Of course on the long run this should be a method for `GenericCharacterType` (see issue #29).
```julia
degree(t::GenericCharacterType) = [...]
```

While we are at it, I wonder: isn't the degree just the first "entry" of the character? If so, why is `T.chardegree`needed at all?

**Comment by SoongNoonien** [comment]
> While we are at it, I wonder: isn't the degree just the first "entry" of the character? If so, why is T.chardegreeneeded at all?

Yes, one would think so. But the first entry of a character is a generic cyclotomic number corresponding to the values for all classes in the first type. Only one of those classes is the trivial class. And in `T.chardegree` are just the values for the trivial class which is the same as the first value of the corresponding character for fixed values for the class parameters. Usually (or always?) these fixed values are just zero. So, yes it should be possible to remove `T.chardegree` or at least to implement `degree` without using `T.chardegree`. But I'm not 100% certain that zero is the right value for the class parameters for every table.
