### ISSUE TITLE
Add tests against the OSCAR book

### ISSUE THREAD

**Issue by lgoettgens** [oscar-system/GenericCharacterTables.jl#89]
To circumvent future breakages as https://github.com/oscar-system/GenericCharacterTables.jl/pull/87 happening.

**Comment by fingolfin** [comment]
To be clear: "breakage" in new semver versions of this package is entirely acceptable from my point of view and a major reason why this is a separate package, not part of OSCAR experimental.

The  book already says that this package is undergoing a major API revision and points out that readers should look at the book website for a revised example. It will also say that the example is compatible with version 0.2.x (the plan is to insert that as part of editing the chapters proofs, once we get them).

The book website then in turn can link to the manual of this book which will carry (once PR #104 is merged) an updated version of the example (we an also put that on the website, if desired, but right not that seems like an unnecessary extra step of work).

**Comment by SoongNoonien** [comment]
We can close this since #104 is merge.
